/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.SyscallController;
import Model.*;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.UIManager;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.Map;
import javax.swing.JScrollPane;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;

/**
 *
 * @author jgfch
 */
public class Gui_Principal extends javax.swing.JFrame {

    private ImageIcon imagen;
    private Icon icono;
    int xMouse, yMouse;
    ProcessManager pm = new ProcessManager();
    DefaultTableModel modelTaskList = new DefaultTableModel();
    SyscallController sys = new SyscallController();
    //boolean resetCsv = false;

    /**
     * Creates new form Gui_Principal
     */
    public Gui_Principal() {

        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }

        initComponents();

        setIconImage(getIconImage());
        this.setLocationRelativeTo(this);
        this.pintarImagen(this.logo, "src/View/Images/ufps.PNG");
        this.pintarImagen(this.logo2, "src/View/Images/logo_ingsistemas_vertical_invertido.png");
    }

    //Icono
    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("View/Images/ufps_Icon.jpg"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        btnExit = new javax.swing.JPanel();
        exitTxt = new javax.swing.JLabel();
        btnHome = new javax.swing.JPanel();
        homeTxt = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        footer = new javax.swing.JLabel();
        image = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        logo2 = new javax.swing.JLabel();
        txt_logo = new javax.swing.JLabel();
        txt2_logo = new javax.swing.JLabel();
        jPanelProcess = new javax.swing.JPanel();
        txtDocumento = new javax.swing.JTextArea();
        btnProcess = new javax.swing.JPanel();
        txtProcess = new javax.swing.JLabel();
        btnCPU = new javax.swing.JPanel();
        txtCPU = new javax.swing.JLabel();
        btnRAM = new javax.swing.JPanel();
        txtRAM = new javax.swing.JLabel();
        btnKill = new javax.swing.JPanel();
        txtKill = new javax.swing.JLabel();
        btnRefresh = new javax.swing.JPanel();
        txtRefresh = new javax.swing.JLabel();
        jLabelBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(1100, 500));
        jPanel1.setPreferredSize(new java.awt.Dimension(1100, 500));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        header.setBackground(new java.awt.Color(0, 0, 0, 0));
        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
        });

        btnExit.setBackground(new java.awt.Color(255, 255, 255));

        exitTxt.setFont(new java.awt.Font("Roboto Light", 0, 36)); // NOI18N
        exitTxt.setText(" X");
        exitTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitTxt.setMaximumSize(new java.awt.Dimension(40, 40));
        exitTxt.setMinimumSize(new java.awt.Dimension(40, 40));
        exitTxt.setPreferredSize(new java.awt.Dimension(40, 40));
        exitTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnExitLayout = new javax.swing.GroupLayout(btnExit);
        btnExit.setLayout(btnExitLayout);
        btnExitLayout.setHorizontalGroup(
            btnExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnExitLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(exitTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        btnExitLayout.setVerticalGroup(
            btnExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exitTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        btnHome.setBackground(new java.awt.Color(255, 255, 255));

        homeTxt.setFont(new java.awt.Font("Roboto Light", 0, 36)); // NOI18N
        homeTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        homeTxt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/home.png")));
        homeTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        homeTxt.setMaximumSize(new java.awt.Dimension(40, 40));
        homeTxt.setMinimumSize(new java.awt.Dimension(40, 40));
        homeTxt.setPreferredSize(new java.awt.Dimension(40, 40));
        homeTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                homeTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                homeTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnHomeLayout = new javax.swing.GroupLayout(btnHome);
        btnHome.setLayout(btnHomeLayout);
        btnHomeLayout.setHorizontalGroup(
            btnHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnHomeLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(homeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        btnHomeLayout.setVerticalGroup(
            btnHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(homeTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addContainerGap(1191, Short.MAX_VALUE)
                .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 40));

        title.setFont(new java.awt.Font("Century Gothic", 0, 48)); // NOI18N
        title.setText("UFPS PROCESS MANAGER");
        jPanel1.add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 60, 600, -1));

        footer.setFont(new java.awt.Font("Quicksand Medium", 2, 16)); // NOI18N
        footer.setText("Developer: José Gabriel Fuentes  |  1152085");
        footer.setToolTipText("");
        jPanel1.add(footer, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 650, 320, 20));

        image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/ads.png")));
        jPanel1.add(image, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 70, 40, 40));

        logo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        logo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 100, 100));
        jPanel1.add(logo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 580, 110, 130));

        txt_logo.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        txt_logo.setForeground(new java.awt.Color(255, 255, 255));
        txt_logo.setText("Universidad Francisco");
        txt_logo.setToolTipText("");
        txt_logo.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(txt_logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, -1, -1));

        txt2_logo.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txt2_logo.setForeground(new java.awt.Color(255, 255, 255));
        txt2_logo.setText("de Paula Santander");
        jPanel1.add(txt2_logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, -1, 30));

        txtDocumento.setEditable(false);
        txtDocumento.setBackground(new java.awt.Color(245, 245, 245));
        txtDocumento.setColumns(20);
        txtDocumento.setFont(new java.awt.Font("Quicksand Medium", 0, 20)); // NOI18N
        txtDocumento.setRows(5);
        txtDocumento.setText("\n\n          A Windows process management software is a tool that allows you to view \n          and manage the processes running on a Windows operating system.\n \n          These programs usually show detailed information of each running process, \n          such as its name, process identifier (PID), CPU usage, RAM memory usage, \n          among other relevant data.\n\n\n     \n\n           After pressing the \"Process List\" button, it will take time depending \n           on all the processes that are running at that instant of time.");

        javax.swing.GroupLayout jPanelProcessLayout = new javax.swing.GroupLayout(jPanelProcess);
        jPanelProcess.setLayout(jPanelProcessLayout);
        jPanelProcessLayout.setHorizontalGroup(
            jPanelProcessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 810, Short.MAX_VALUE)
            .addGroup(jPanelProcessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelProcessLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(txtDocumento)
                    .addContainerGap()))
        );
        jPanelProcessLayout.setVerticalGroup(
            jPanelProcessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
            .addGroup(jPanelProcessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelProcessLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(19, Short.MAX_VALUE)))
        );

        jPanel1.add(jPanelProcess, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 140, 810, 440));

        btnProcess.setBackground(new java.awt.Color(211, 89, 88));

        txtProcess.setFont(new java.awt.Font("Roboto Medium", 0, 15)); // NOI18N
        txtProcess.setForeground(new java.awt.Color(255, 255, 255));
        txtProcess.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtProcess.setText("Process list");
        txtProcess.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtProcess.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtProcessMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtProcessMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtProcessMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnProcessLayout = new javax.swing.GroupLayout(btnProcess);
        btnProcess.setLayout(btnProcessLayout);
        btnProcessLayout.setHorizontalGroup(
            btnProcessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtProcess, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        btnProcessLayout.setVerticalGroup(
            btnProcessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtProcess, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel1.add(btnProcess, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 170, 110, 50));

        btnCPU.setBackground(new java.awt.Color(211, 89, 88));

        txtCPU.setFont(new java.awt.Font("Roboto Medium", 0, 15)); // NOI18N
        txtCPU.setForeground(new java.awt.Color(255, 255, 255));
        txtCPU.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtCPU.setText("CPU Plot");
        txtCPU.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtCPU.setEnabled(false);
        txtCPU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtCPUMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtCPUMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtCPUMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnCPULayout = new javax.swing.GroupLayout(btnCPU);
        btnCPU.setLayout(btnCPULayout);
        btnCPULayout.setHorizontalGroup(
            btnCPULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtCPU, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        btnCPULayout.setVerticalGroup(
            btnCPULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtCPU, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel1.add(btnCPU, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, 110, 50));

        btnRAM.setBackground(new java.awt.Color(211, 89, 88));

        txtRAM.setFont(new java.awt.Font("Roboto Medium", 0, 15)); // NOI18N
        txtRAM.setForeground(new java.awt.Color(255, 255, 255));
        txtRAM.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtRAM.setText("RAM Plot");
        txtRAM.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtRAM.setEnabled(false);
        txtRAM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtRAMMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtRAMMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtRAMMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnRAMLayout = new javax.swing.GroupLayout(btnRAM);
        btnRAM.setLayout(btnRAMLayout);
        btnRAMLayout.setHorizontalGroup(
            btnRAMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtRAM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        btnRAMLayout.setVerticalGroup(
            btnRAMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtRAM, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel1.add(btnRAM, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 310, 110, 50));

        btnKill.setBackground(new java.awt.Color(211, 89, 88));

        txtKill.setFont(new java.awt.Font("Roboto Medium", 0, 15)); // NOI18N
        txtKill.setForeground(new java.awt.Color(255, 255, 255));
        txtKill.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtKill.setText("Kill Process");
        txtKill.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtKill.setEnabled(false);
        txtKill.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtKillMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtKillMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtKillMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnKillLayout = new javax.swing.GroupLayout(btnKill);
        btnKill.setLayout(btnKillLayout);
        btnKillLayout.setHorizontalGroup(
            btnKillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnKillLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(txtKill, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        btnKillLayout.setVerticalGroup(
            btnKillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnKillLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(txtKill, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(btnKill, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 380, 110, 50));

        btnRefresh.setBackground(new java.awt.Color(211, 89, 88));

        txtRefresh.setFont(new java.awt.Font("Roboto Medium", 0, 15)); // NOI18N
        txtRefresh.setForeground(new java.awt.Color(255, 255, 255));
        txtRefresh.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtRefresh.setText("Refresh Process");
        txtRefresh.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtRefresh.setEnabled(false);
        txtRefresh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtRefreshMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtRefreshMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtRefreshMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnRefreshLayout = new javax.swing.GroupLayout(btnRefresh);
        btnRefresh.setLayout(btnRefreshLayout);
        btnRefreshLayout.setHorizontalGroup(
            btnRefreshLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtRefresh, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
        );
        btnRefreshLayout.setVerticalGroup(
            btnRefreshLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnRefreshLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(txtRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(btnRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 590, 160, 50));

        jLabelBackground.setBackground(new java.awt.Color(255, 255, 255));
        jLabelBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/city2.png")));
        jPanel1.add(jLabelBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1280, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 670, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxtMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitTxtMouseClicked

    private void exitTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxtMouseEntered
        btnExit.setBackground(new java.awt.Color(190, 0, 0));
        exitTxt.setForeground(Color.white);
    }//GEN-LAST:event_exitTxtMouseEntered

    private void exitTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxtMouseExited
        btnExit.setBackground(Color.white);
        exitTxt.setForeground(Color.black);
    }//GEN-LAST:event_exitTxtMouseExited

    private void homeTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeTxtMouseClicked
        Gui_Principal guiP = new Gui_Principal();
        guiP.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_homeTxtMouseClicked

    private void homeTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeTxtMouseEntered
        btnHome.setBackground(new java.awt.Color(190, 0, 0));
        homeTxt.setForeground(Color.white);
    }//GEN-LAST:event_homeTxtMouseEntered

    private void homeTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeTxtMouseExited
        btnHome.setBackground(Color.white);
        homeTxt.setForeground(Color.black);
    }//GEN-LAST:event_homeTxtMouseExited

    private void headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_headerMouseDragged

    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_headerMousePressed


    private void txtProcessMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtProcessMouseClicked
        try {
            createJTable();
            sys.threadTaskList(modelTaskList);
        } catch (IOException | InterruptedException ex) {
            Logger.getLogger(Gui_Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.txtCPU.setEnabled(true);
        this.txtRAM.setEnabled(true);
        this.txtKill.setEnabled(true);
        this.txtRefresh.setEnabled(true);
        this.jPanelProcess.remove(this.txtDocumento);
    }//GEN-LAST:event_txtProcessMouseClicked

    private void createJTable() throws IOException, FileNotFoundException, InterruptedException {
        int x = 430;
        int y = 140;
        int width = 810;
        int height = 440;

        JTable jTable = new javax.swing.JTable() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // Hace que todas las celdas sean no editables
            }
        };
        jTable.setModel(modelTaskList);
        modelTaskList.setColumnIdentifiers(new Object[]{"Nombre de imagen", "PID",
            "Uso de memoria", "Tiempo de CPU"});

        jTable.getTableHeader().setReorderingAllowed(false);
        // Configurar ancho de columna específica
        jTable.getColumnModel().getColumn(0).setPreferredWidth(100);
        jTable.getColumnModel().getColumn(1).setPreferredWidth(50);
        //jTable.getColumnModel().getColumn(2).setPreferredWidth(100);
        //jTable.getColumnModel().getColumn(3).setPreferredWidth(40);
        jTable.getColumnModel().getColumn(2).setPreferredWidth(100);
        //jTable.getColumnModel().getColumn(6).setPreferredWidth(105);
        jTable.getColumnModel().getColumn(3).setPreferredWidth(90);
        //jTable.getColumnModel().getColumn(8).setPreferredWidth(100);

        JScrollPane jScrollPane = new JScrollPane(jTable);
        jScrollPane.setBounds(x, y, width, height);

        getContentPane().add(jScrollPane);
        jScrollPane.setEnabled(true);
        jTable.setEnabled(true);
        jTable.getTableHeader().setReorderingAllowed(false);
    }

    private void txtProcessMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtProcessMouseEntered
        this.btnProcess.setBackground(new java.awt.Color(176, 21, 14));
        this.txtProcess.setForeground(Color.white);
    }//GEN-LAST:event_txtProcessMouseEntered

    private void txtProcessMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtProcessMouseExited
        this.btnProcess.setBackground(new java.awt.Color(211, 89, 88));
        this.txtProcess.setForeground(Color.white);
    }//GEN-LAST:event_txtProcessMouseExited

    private void txtRAMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtRAMMouseClicked
        if (this.txtRAM.isEnabled()) {
            if (sys.getMapData() == null) {
                sys.setMapData(sys.mapCpuRam(sys.getCsvData()));
                pieChartCpu(sys.getMapData());
            } else {
                pieChartRam(sys.getMapData());
            }

        }
    }//GEN-LAST:event_txtRAMMouseClicked

    private void pieChartRam(Map<String, ArrayList<String[]>> dataMap) {
        JFreeChart pieChart = ChartFactory.createPieChart("RAM", sys.createPieChartRam(dataMap), true, true, false);
        ChartPanel panel = new ChartPanel(pieChart);
        panel.setMouseWheelEnabled(true);
        panel.setPreferredSize(new Dimension(1450, 850));

        JPanel panelRam = new JPanel();
        panelRam.setLayout(new BorderLayout());
        panelRam.add(panel, BorderLayout.NORTH);
        createJframe(panelRam);
    }

    public void createJframe(JPanel panel) {
        javax.swing.JFrame frame = new javax.swing.JFrame();
        frame.setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE);
        frame.getContentPane().add(panel);
        frame.pack();
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);
    }

    private void txtRAMMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtRAMMouseEntered
        this.btnRAM.setBackground(new java.awt.Color(176, 21, 14));
        this.txtRAM.setForeground(Color.white);
    }//GEN-LAST:event_txtRAMMouseEntered

    private void txtRAMMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtRAMMouseExited
        this.btnRAM.setBackground(new java.awt.Color(211, 89, 88));
        this.txtRAM.setForeground(Color.white);
    }//GEN-LAST:event_txtRAMMouseExited

    private void txtKillMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtKillMouseClicked
        if (this.txtKill.isEnabled()) {
            try {
                optionsKill();
            } catch (InterruptedException | IOException ex) {
                Logger.getLogger(Gui_Principal.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_txtKillMouseClicked

    private void optionsKill() throws InterruptedException, IOException {
        JOptionPane.showMessageDialog(null, "To kill a task, it can be done by \"Process ID\" or \"Process Name\"", "How to use",
                JOptionPane.WARNING_MESSAGE);

        String[] options = {"Id", "Name"};
        int select = JOptionPane.showOptionDialog(null, "How do you want to kill a process?", "Kill Process", JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE, null, options, options[0]);

        JPanel myPanel = new JPanel();
        JTextField processID = null, processName = null;
        boolean aux = true;
        if (select == 0) {
            processID = new JTextField(10);
            myPanel.add(new JLabel("Process ID:"));
            myPanel.add(processID);
        } else if (select == 1) {
            aux = false;
            processName = new JTextField(10);
            myPanel.add(new JLabel("Process Name (Example: notepad.exe):"));
            myPanel.add(processName);
        }
        int result = JOptionPane.showConfirmDialog(null, myPanel,
                "Kill Process", JOptionPane.OK_CANCEL_OPTION, JOptionPane.ERROR_MESSAGE);

        if (result == JOptionPane.OK_OPTION) {
            String task = "";
            try {
                if (aux) {
                    String id = processID.getText();
                    if (id.equals("0")) {
                        JOptionPane.showMessageDialog(null, "Error, el proceso con PID: " + id + " no se puede finalizar\nMotivo: Es un proceso critico del sistema. Taskill can´t kill this process", "Error, the task couldn't be killed",
                                JOptionPane.WARNING_MESSAGE);
                        return;
                    } else {
                        task = pm.executeTaskKillId(id);
                    }
                } else {
                    String name = processName.getText();
                    task = pm.executeTaskKillName(name);
                }
            } catch (IOException | InterruptedException ex) {
                Logger.getLogger(Gui_Principal.class.getName()).log(Level.SEVERE, null, ex);
            }
            JOptionPane.showMessageDialog(null, "Correcto: se terminó el" + task, "Successful,  task has been killed",
                    JOptionPane.INFORMATION_MESSAGE);
            modelTaskList.setRowCount(0);
            sys.generateTaskList(modelTaskList);
        }
    }

    private void txtKillMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtKillMouseEntered
        this.btnKill.setBackground(new java.awt.Color(176, 21, 14));
        this.txtKill.setForeground(Color.white);
    }//GEN-LAST:event_txtKillMouseEntered

    private void txtKillMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtKillMouseExited
        this.btnKill.setBackground(new java.awt.Color(211, 89, 88));
        this.txtKill.setForeground(Color.white);
    }//GEN-LAST:event_txtKillMouseExited

    private void txtCPUMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCPUMouseClicked
        if (this.txtCPU.isEnabled()) {
            if (sys.getMapData() == null) {
                sys.setMapData(sys.mapCpuRam(sys.getCsvData()));
                pieChartCpu(sys.getMapData());
            } else {
                pieChartCpu(sys.getMapData());
            }

        }
    }//GEN-LAST:event_txtCPUMouseClicked

    private void pieChartCpu(Map<String, ArrayList<String[]>> dataMap) {
        JFreeChart pieChart = ChartFactory.createPieChart("CPU", sys.createPieChartCpu(dataMap), true, true, false);
        ChartPanel panel = new ChartPanel(pieChart);
        panel.setMouseWheelEnabled(true);
        panel.setPreferredSize(new Dimension(1450, 850));

        JPanel panelCpu = new JPanel();
        panelCpu.setLayout(new BorderLayout());
        panelCpu.add(panel, BorderLayout.NORTH);
        createJframe(panelCpu);
    }

    private void txtCPUMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCPUMouseEntered
        this.btnCPU.setBackground(new java.awt.Color(176, 21, 14));
        this.txtCPU.setForeground(Color.white);
    }//GEN-LAST:event_txtCPUMouseEntered

    private void txtCPUMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCPUMouseExited
        this.btnCPU.setBackground(new java.awt.Color(211, 89, 88));
        this.txtCPU.setForeground(Color.white);
    }//GEN-LAST:event_txtCPUMouseExited

    private void txtRefreshMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtRefreshMouseClicked
        if (this.txtRefresh.isEnabled()) {
            try {
                sys.generateTaskList(modelTaskList);
            } catch (IOException | InterruptedException ex) {
                Logger.getLogger(Gui_Principal.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_txtRefreshMouseClicked

    private void txtRefreshMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtRefreshMouseEntered
        this.btnRefresh.setBackground(new java.awt.Color(176, 21, 14));
        this.txtRefresh.setForeground(Color.white);
    }//GEN-LAST:event_txtRefreshMouseEntered

    private void txtRefreshMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtRefreshMouseExited
        this.btnRefresh.setBackground(new java.awt.Color(211, 89, 88));
        this.txtRefresh.setForeground(Color.white);
    }//GEN-LAST:event_txtRefreshMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gui_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gui_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gui_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gui_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gui_Principal().setVisible(true);
            }
        });
    }

    public void pintarImagen(JLabel lbl, String ruta) {
        this.imagen = new ImageIcon(ruta);
        this.icono = new ImageIcon(this.imagen.getImage().getScaledInstance(lbl.getWidth(), lbl.getHeight(), Image.SCALE_DEFAULT));

        lbl.setIcon(this.icono);
        this.repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnCPU;
    private javax.swing.JPanel btnExit;
    private javax.swing.JPanel btnHome;
    private javax.swing.JPanel btnKill;
    private javax.swing.JPanel btnProcess;
    private javax.swing.JPanel btnRAM;
    private javax.swing.JPanel btnRefresh;
    private javax.swing.JLabel exitTxt;
    private javax.swing.JLabel footer;
    private javax.swing.JPanel header;
    private javax.swing.JLabel homeTxt;
    private javax.swing.JLabel image;
    private javax.swing.JLabel jLabelBackground;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelProcess;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel logo2;
    private javax.swing.JLabel title;
    private javax.swing.JLabel txt2_logo;
    private javax.swing.JLabel txtCPU;
    private javax.swing.JTextArea txtDocumento;
    private javax.swing.JLabel txtKill;
    private javax.swing.JLabel txtProcess;
    private javax.swing.JLabel txtRAM;
    private javax.swing.JLabel txtRefresh;
    private javax.swing.JLabel txt_logo;
    // End of variables declaration//GEN-END:variables
}
